### PR TITLE
Fix FGTS-210: Prevent multiple damage per frame

### PR DESCRIPTION
**Pull request by charasyn**
This prevents the bug I sent in the Teams chat, which can hardlock the game.

### CODE REVIEW

**Comment by fheysel** [comment]
Is there any way we can limit this to death-plane interactions? If a bird and a rat hit the player at the same time I feel like they should take damage from both

**Comment by charasyn** [comment]
That's not really consistent, if a bird and rat hit the player "at the same time" normally it wouldn't be on the same frame, so only one of them would go through because the other would be blocked by i-frames. If they hit same frame then it would deal double damage but would feel arbitrary to the user most likely.

**Comment by fheysel** [comment]
how is the player able to hit 2 vats of acid at the same time? Wouldn't they also be blocked by i-frames?

**Comment by charasyn** [comment]
Nope, vat of acid defers the application of knockback/i-frames by one frame in order to avoid glitchy audio effects (where the audio starts playing before warping the player but then gets cutoff by the transition, resulting in a short clip of noise then the transition then the rest of the sound effect).

**Comment by charasyn** [comment]
Acid also ignores i-frames

**Pull request merged**
