### PR TITLE
Add new control schemes to game

### PR DESCRIPTION
**Pull request by charasyn**
Current controls:
WASD / Arrows - Move character
Enter / Space / Z - Jump
Shift / X - Tongue
Escape / C - Menu

### CODE REVIEW

**Comment by charasyn** [comment]
Lmk if there are any more controls that I should add. I didn't add Q / E as bound controls because if people are using WASD, they're going to need to be pressing WASD at the same time as they jump or tongue. I think we also discussed adding J / K / L as alternatives to Z / X / C? Let me know if I should add those.

**Review by fheysel — COMMENTED** [review]
I think this should be enough variety for people. Has the in game menu been updated to reflect the new options?

**Comment by charasyn** [comment]
Nope, not yet. I'll do it 👍

**Comment by charasyn** [comment]
OK. This should be ready to go now

**Pull request merged**
