### PR TITLE
FGTS-49: Add adjusting of frog tongue radius, with min and max parameters

### PR DESCRIPTION
**Pull request by charasyn**
This change addresses JIRA issue FGTS-49: "Frog should be able to change tongue radius"

### Added mechanic: adjusting tongue radius
When the frog is in the "swinging on tongue" state, the user can press up/down on the joystick to retract/extend the frog's tongue (the swing radius). There will be a maximum and minimum swing radius past which the user will not be able to adjust the radius.
When attempting to adjust the radius, collision detection will be performed to ensure that the radius cannot be adjusted in a manner that puts the frog in an invalid position.

### CODE REVIEW

**Comment by jDenyes** [comment]
test

**Review by jDenyes — APPROVED** [review]

**Comment by fheysel** [comment]
I think we decided to scrap this functionality.  If thats the case this branch should be closed

**Comment by charasyn** [comment]
Question about this PR: we discussed potentially having the tongue extend and snap if the user is using the tongue for too long right? I think that could use this functionality maybe, so I think that it might be a good idea to keep the code in to change the tongue radius, but not allow the user to control it. How does that sound?

**Comment by fheysel** [comment]
Im fine with leaving it open until a later date

**Comment by fheysel** [comment]
Closed for now, if we end up deciding we want this functionality we can reintroduce in new PR

**Pull request closed without merging**
